2012-11-09 19:11:33.760 [error] <0.309.0>@ct_client_command:execute:29 ct_client_command: error {badmatch,{error,sql_error}} [{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,63}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,14}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:11:33.833 [error] <0.309.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[{badmatch,{error,sql_error}}],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:16:45.103 [error] <0.314.0>@ct_client_command:execute:29 ct_client_command: error {badmatch,{error,sql_error}} [{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,63}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,14}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:16:45.166 [error] <0.314.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[{badmatch,{error,sql_error}}],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:16:54.038 [error] <0.319.0>@ct_client_command:execute:29 ct_client_command: error {badmatch,{error,sql_error}} [{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,63}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,14}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:16:54.106 [error] <0.319.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[{badmatch,{error,sql_error}}],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:17:29.220 [error] <0.309.0> gen_server <0.309.0> terminated with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87
2012-11-09 19:17:29.330 [error] <0.309.0> CRASH REPORT Process <0.309.0> with 0 neighbours exited with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87 in gen_server:terminate/6 line 747
2012-11-09 19:17:29.417 [error] <0.314.0> gen_server <0.314.0> terminated with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87
2012-11-09 19:17:29.501 [error] <0.314.0> CRASH REPORT Process <0.314.0> with 0 neighbours exited with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87 in gen_server:terminate/6 line 747
2012-11-09 19:17:29.569 [error] <0.319.0> gen_server <0.319.0> terminated with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87
2012-11-09 19:17:29.609 [error] <0.319.0> CRASH REPORT Process <0.319.0> with 0 neighbours exited with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87 in gen_server:terminate/6 line 747
2012-11-09 19:17:36.197 [error] <0.326.0>@ct_client_command:execute:29 ct_client_command: error {badmatch,{error,sql_error}} [{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,63}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,14}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:17:36.287 [error] <0.326.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[{badmatch,{error,sql_error}}],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:18:49.050 [error] <0.331.0>@ct_client_command:execute:29 ct_client_command: error {badmatch,{error,sql_error}} [{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,63}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,14}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:18:49.121 [error] <0.331.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[{badmatch,{error,sql_error}}],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:22:42.086 [error] <0.326.0> gen_server <0.326.0> terminated with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87
2012-11-09 19:22:42.157 [error] <0.326.0> CRASH REPORT Process <0.326.0> with 0 neighbours exited with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87 in gen_server:terminate/6 line 747
2012-11-09 19:33:22.163 [error] <0.309.0>@ct_client_command:execute:29 ct_client_command: error {badmatch,{error,sql_error}} [{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,63}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,14}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:33:22.227 [error] <0.309.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[{badmatch,{error,sql_error}}],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:37:33.266 [error] <0.314.0>@ct_client_command:execute:29 ct_client_command: error badarg [{erlang,list_to_atom,[1005],[]},{ct_player_sup,start_player,1,[{file,"src/ct_player_sup.erl"},{line,27}]},{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,75}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,14}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]}].
2012-11-09 19:37:33.336 [error] <0.314.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[badarg],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:37:51.470 [error] <0.321.0>@ct_client_command:execute:29 ct_client_command: error badarg [{erlang,list_to_atom,[1002],[]},{ct_player_sup,start_player,1,[{file,"src/ct_player_sup.erl"},{line,27}]},{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,75}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,14}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]}].
2012-11-09 19:37:51.577 [error] <0.321.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[badarg],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:38:38.059 [error] <0.328.0>@ct_client_command:execute:29 ct_client_command: error badarg [{erlang,list_to_atom,[1001],[]},{ct_player_sup,start_player,1,[{file,"src/ct_player_sup.erl"},{line,27}]},{ct_client_command,do_command,2,[{file,"src/ct_client_command.erl"},{line,75}]},{ct_client_command,execute,2,[{file,"src/ct_client_command.erl"},{line,14}]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,45}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]}].
2012-11-09 19:38:38.123 [error] <0.328.0>@ct_yaws_catacomb_ws_endpoint:handle_message:52 Error in ct_yaws_catacomb_ws_endpoint: error badarg [{erlang,list_to_binary,[badarg],[]},{ct_yaws_catacomb_ws_endpoint,handle_message,2,[{file,"src/ct_yaws_catacomb_ws_endpoint.erl"},{line,49}]},{yaws_websockets,'-do_callback_fun/2-fun-0-',4,[{file,"src/yaws_websockets.erl"},{line,257}]},{lists,foldl,3,[{file,"lists.erl"},{line,1197}]},{yaws_websockets,handle_info,2,[{file,"src/yaws_websockets.erl"},{line,147}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,607}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}].
2012-11-09 19:38:49.311 [error] <0.309.0> gen_server <0.309.0> terminated with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87
2012-11-09 19:38:49.383 [error] <0.309.0> CRASH REPORT Process <0.309.0> with 0 neighbours exited with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87 in gen_server:terminate/6 line 747
2012-11-09 19:41:43.598 [error] <0.314.0> gen_server <0.314.0> terminated with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87
2012-11-09 19:41:43.638 [error] <0.314.0> CRASH REPORT Process <0.314.0> with 0 neighbours exited with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87 in gen_server:terminate/6 line 747
2012-11-09 19:42:27.738 [error] <0.321.0> gen_server <0.321.0> terminated with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87
2012-11-09 19:42:27.803 [error] <0.321.0> CRASH REPORT Process <0.321.0> with 0 neighbours exited with reason: bad record state in ct_yaws_catacomb_ws_endpoint:handle_message/2 line 87 in gen_server:terminate/6 line 747
2012-11-09 20:07:57.718 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-09 20:08:03.180 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-09 20:42:29.854 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-09 20:45:22.487 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-09 21:42:20.921 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
2012-11-09 21:44:18.125 [error] <0.77.0> Supervisor ct_yaws_sup had child ct_yaws_start started with ct_yaws_start:start() at <0.78.0> exit with reason noproc in context shutdown_error
